# modules/mail/mbsync.nix
{ config, lib, pkgs, ... }:

let
  cfg = config.yuko.debug;
  inherit (cfg) logStep;
  accountName = config.yuko.mail.activeAccount;
  hmAccount = config.yuko.mail.activeHmAccount;
  yukoAccount = config.yuko.mail.activeAccountMeta;
  maildirBase = yukoAccount.maildirBasePath;
  passEntry = yukoAccount.imapPassEntry;
in

lib.mkIf (config.home.username == "trynn") {
  
  # Ensure isync/mbsync is installed
  home.packages = [ pkgs.isync ];

  # Create the Maildir skeleton so mbsync has somewhere to write
  home.activation.createMaildir = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    mkdir -p ${lib.escapeShellArg maildirBase}/Inbox/{cur,new,tmp}
  '';

  # Main isync/mbsync config
  xdg.configFile."isyncrc".text = ''
    # Generated by Home Manager (YukoNix mbsync)
    IMAPAccount ${accountName}
      Host ${hmAccount.imap.host}
      Port ${toString hmAccount.imap.port}
      User ${hmAccount.userName or hmAccount.address}
      TLSType IMAPS
      CertificateFile /etc/ssl/certs/ca-certificates.crt
      PassCmd "${pkgs.pass}/bin/pass show ${passEntry}"

    IMAPStore ${accountName}-remote
      Account ${accountName}

    MaildirStore ${accountName}-local
      Path ${maildirBase}/
      Inbox ${maildirBase}/Inbox
      SubFolders Verbatim

    Channel ${accountName}
      Far :${accountName}-remote:
      Near :${accountName}-local:
      Patterns *
      Create Both
      Expunge None
      Remove None
      SyncState *
  '';

  # Preflight: make sure the pass secret exists
  home.activation.mbsyncPreflight = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    if ! ${pkgs.pass}/bin/pass show ${passEntry} >/dev/null 2>&1; then
      echo "YukoNix: pass entry '${passEntry}' not found or unreadable."
      echo " Create it with:"
      echo " pass insert ${passEntry}"
      ${logStep { component = "mail/mbsync"; message = "Missing IMAP password in pass for ${accountName}: pass insert ${passEntry}"; }}
    fi
  '';
}

