# modules/mail/msmtp.nix
{ config, lib, pkgs, ... }:

let
  cfg = config.yuko.debug;
  inherit (cfg) logStep;
  accountName = config.yuko.mail.activeAccount;
  hmAccount = config.yuko.mail.activeHmAccount;
  yukoAccount = config.yuko.mail.activeAccountMeta;
  mailLog = "$HOME/.yuko/logs/mail/msmtp.log";
  # Accessing yukoAccount.smtpPassEntry here is safe because its value is only
  # evaluated if the 'lib.mkIf' condition is met below (preventing 'null' access).
  passEntry = yukoAccount.smtpPassEntry; 
in
  imports = [
    # 1. Imports custom options defined in core (e.g., activeHmAccount)
    ../../core.nix 
    
    # makes the submodule self-contained and avoids errors when modules are conditionally included.
    (import "${pkgs.home-manager}/modules/programs/msmtp.nix")
  ];

  lib.mkIf (config.home.username == "trynn") {
  
    # Configuration Block (returned only for 'trynn' user)
    programs.msmtp = {
      enable = true;
      # Full msmtp config (goes to ~/.config/msmtp/config)
      configContent = ''
        # Generated by Home Manager (YukoNix msmtp)
        defaults
          auth on
          tls on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt
          logfile ${mailLog}

        account ${accountName}
          host ${hmAccount.smtp.host}
          port ${toString hmAccount.smtp.port}
          from ${hmAccount.address}
          user ${hmAccount.userName or hmAccount.address}
          passwordeval "${pkgs.pass}/bin/pass show ${passEntry}"

        account default : ${accountName}
      '';
    };

    # Preflight: make sure SMTP secret exists and log directory can be used
    home.activation.msmtpPreflight = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      mkdir -p "$(dirname ${mailLog})"
      
      if ! ${pkgs.pass}/bin/pass show ${passEntry} >/dev/null 2>&1; then
        echo "YukoNix: pass entry '${passEntry}' not found or unreadable."
        echo " Create it with:"
        echo " pass insert ${passEntry}"
        ${logStep { component = "mail/msmtp"; message = "Missing SMTP password in pass for ${accountName}: pass insert ${passEntry}"; }}
      fi
    '';
}

