# modules/composer/aider.nix
{ config, lib, pkgs, ... }:

let
  cfg = config.yuko.composer.aider;
  yukoDir = "${config.home.homeDirectory}/.yuko";
  # Reference the tags generated by your ctags.nix
  tagsFile = "${yukoDir}/.tags/tags";
in {
  options.yuko.composer.aider.enable = lib.mkEnableOption "Local Aider Composer";

  config = lib.mkIf cfg.enable {
    home.packages = [ pkgs.aider-chat ];

    # Aider configuration optimized for local 8GB VRAM models
    home.file.".aider.conf.yml".text = ''
      openai-api-base: http://localhost:8081/v1
      openai-api-key: "local"
      model: openai/qwen-coder
      architect: true
      edit-format: architect
      vim: true
      dark-mode: true
      # INCREASE TIMEOUT: Give the 4060 time to ingest the 1.7k tokens
      timeout: 300 
      # Use a smaller map to reduce the initial token burst
      map-tokens: 512
    '';

    # A helper script to ensure the environment is ready
    home.file.".local/bin/yuko-compose".source = pkgs.writeShellScript "yuko-compose" ''
      echo "Checking LocalAI status..."
      if ! ${pkgs.curl}/bin/curl -s http://localhost:8081/v1/models > /dev/null; then
        echo "LocalAI not responding on port 8081. Please check sudo systemctl status podman-local-ai"
        exit 1
      fi
      # Clean call without the --map-file flag
      ${pkgs.aider-chat}/bin/aider "$@"
    '';
  };
}
